steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMAGE_NAME'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_IMAGE_NAME'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_IMAGE_NAME'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'

images:
  - '$_IMAGE_NAME'

substitutions:
  _IMAGE_NAME: 'gcr.io/$PROJECT_ID/llm-guard-web-client:$SHORT_SHA'
  _SERVICE_NAME: 'llm-guard-web-client'
  _REGION: 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY
