steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llm-guard-web-client:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llm-guard-web-client:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/llm-guard-web-client'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'llm-guard-web-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/llm-guard-web-client:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/llm-guard-web-client:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/llm-guard-web-client:latest'

options:
  logging: CLOUD_LOGGING_ONLY
